name       : karchive
version    : 5.50.0
release    : 20
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.50/karchive-5.50.0.tar.xz : 5420a1d94f699415aa3587ca44f631be62c7c8bcac5a813dd70099d7b66701ca
license    :
    - GPL-2.0
    - LGPL-2.1
component  : programming
optimize   : lto
summary    : Reading, creating, and manipulating file archives.
description: |
    Reading, creating, and manipulating file archives.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - bzip2-devel
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
