name       : karchive
version    : 5.74.0
release    : 43
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.74/karchive-5.74.0.tar.xz : deba7aedd9cbf707a56cabeb33d231d64db36c3e5ff866b543c374613be1fc21
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.library
optimize   : lto
summary    : Reading, creating, and manipulating file archives.
description: |
    Reading, creating, and manipulating file archives.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - bzip2-devel
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
        -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
