name       : karchive
version    : 5.59.0
release    : 29
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.59/karchive-5.59.0.tar.xz : d95623a2cc024965d135a09e4bd1d860cef33e11db41b0ef3110548fa5d63523
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Reading, creating, and manipulating file archives.
description: |
    Reading, creating, and manipulating file archives.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - bzip2-devel
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
