name       : karchive
version    : 5.107.0
release    : 71
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.107/karchive-5.107.0.tar.xz : e88cb94b9af8a88f360e627b3ae7a2b99ccdfe3fe9e1961452056b2a00f04a7f
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.0-or-later
component  : programming.library
summary    : Reading, creating, and manipulating file archives.
description: |
    Reading, creating, and manipulating file archives.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Designer)
    - pkgconfig(liblzma)
    - pkgconfig(libzstd)
    - bzip2-devel
    - extra-cmake-modules
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
        -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
