name       : karchive
version    : 5.75.0
release    : 44
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.75/karchive-5.75.0.tar.xz : 0c833c766d2301335490a1b36197bae20b2e45d1350f4f8100e6e00d5502eaab
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.0-or-later
component  : programming.library
optimize   : lto
summary    : Reading, creating, and manipulating file archives.
description: |
    Reading, creating, and manipulating file archives.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - bzip2-devel
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
        -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
