name       : karchive
version    : 5.71.0
release    : 41
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.71/karchive-5.71.0.tar.xz : cc81e856365dec2bcf3ec78aa01d42347ca390a2311ea12050f309dfbdb09624
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.library
optimize   : lto
summary    : Reading, creating, and manipulating file archives.
description: |
    Reading, creating, and manipulating file archives.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - bzip2-devel
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
        -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
