name       : karchive
version    : 5.56.0
release    : 26
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.56/karchive-5.56.0.tar.xz : 281a6cea68d19d56f8506e839e450d6652604e49ab70b540e29828b50adbcad6
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Reading, creating, and manipulating file archives.
description: |
    Reading, creating, and manipulating file archives.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - bzip2-devel
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
