name       : karchive
version    : 5.62.0
release    : 32
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.62/karchive-5.62.0.tar.xz : 99980ebdc16dd9ac062fcfda0974c0ce894c09a395caf914518646ffdc48e3ca
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Reading, creating, and manipulating file archives.
description: |
    Reading, creating, and manipulating file archives.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - bzip2-devel
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
