name       : karchive
version    : 5.35.0
release    : 5
source     :
    - https://download.kde.org/stable/frameworks/5.35/karchive-5.35.0.tar.xz : 86595e976f8de6c7c12901c29ee579dd31490370867e72e8308e4e3e11010cca
license    :
    - GPL-2.0
    - LGPL-2.1
component  : programming
summary    : Reading, creating, and manipulating file archives.
description: |
    Reading, creating, and manipulating file archives.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
