name       : karchive
version    : 5.60.0
release    : 30
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.60/karchive-5.60.0.tar.xz : 4e3d2a6ba551c6ada44a6517150e031df92691919119bc3b5eb4efc741ff7564
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Reading, creating, and manipulating file archives.
description: |
    Reading, creating, and manipulating file archives.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - bzip2-devel
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
