name       : karchive
version    : 5.53.0
release    : 23
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.53/karchive-5.53.0.tar.xz : 794350830a213336f5488e54916a81e71d1271e1cd65de92e3becffc550a7949
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Reading, creating, and manipulating file archives.
description: |
    Reading, creating, and manipulating file archives.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - bzip2-devel
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
