name       : karchive
version    : 5.61.0
release    : 31
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.61/karchive-5.61.0.tar.xz : 457ed420449630625cb161fcc9bedc7c6a16527f48d6db4008aea76cdb948387
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Reading, creating, and manipulating file archives.
description: |
    Reading, creating, and manipulating file archives.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - bzip2-devel
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
