name       : karchive
version    : 5.109.0
release    : 72
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.109/karchive-5.109.0.tar.xz : 9c4a01c2e4190824e901d487aaa8ce6b2731aa8254fddd9c1a25ee1d1bbbc966
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.0-or-later
component  : programming.library
summary    : Reading, creating, and manipulating file archives.
description: |
    Reading, creating, and manipulating file archives.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Designer)
    - pkgconfig(liblzma)
    - pkgconfig(libzstd)
    - bzip2-devel
    - extra-cmake-modules
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
        -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
