name       : karchive
version    : 5.100.0
release    : 67
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.100/karchive-5.100.0.tar.xz : f5ae507b0ceca71229017128997e12eff51b697ca2a1a37b729f9253ebfe969b
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.0-or-later
component  : programming.library
summary    : Reading, creating, and manipulating file archives.
description: |
    Reading, creating, and manipulating file archives.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Designer)
    - bzip2-devel
    - extra-cmake-modules
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
        -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
