name       : karchive
version    : 5.69.0
release    : 39
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.69/karchive-5.69.0.tar.xz : 1a9555eadb72909adbf512e476db29abb5223e736b3c3b77b47753c1138aa039
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.library
optimize   : lto
summary    : Reading, creating, and manipulating file archives.
description: |
    Reading, creating, and manipulating file archives.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - bzip2-devel
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
        -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
