name       : karchive
version    : 5.38.0
release    : 7
source     :
    - https://download.kde.org/stable/frameworks/5.38/karchive-5.38.0.tar.xz : 9354d45219342b888ac0eccbc3ce3a054858fcce9d4c93817352d2b447ebb658
license    :
    - GPL-2.0
    - LGPL-2.1
component  : programming
summary    : Reading, creating, and manipulating file archives.
description: |
    Reading, creating, and manipulating file archives.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - bzip2-devel
    - extra-cmake-modules
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
check      : |
    %make test
