name       : karchive
version    : 5.77.0
release    : 46
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.77/karchive-5.77.0.tar.xz : 2239af811b9205d9f4486791f4b25ff5ea299b3873021a646e1c8b9d44c2be36
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.0-or-later
component  : programming.library
optimize   : lto
summary    : Reading, creating, and manipulating file archives.
description: |
    Reading, creating, and manipulating file archives.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - bzip2-devel
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
        -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
