name       : karchive
version    : 5.42.0
release    : 11
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.42/karchive-5.42.0.tar.xz : 71e130280953918ddbabc1731c65d16923ab96313bb3c6e58786b6dadbb302ef
license    :
    - GPL-2.0
    - LGPL-2.1
component  : programming
optimize   : lto
summary    : Reading, creating, and manipulating file archives.
description: |
    Reading, creating, and manipulating file archives.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - bzip2-devel
    - extra-cmake-modules
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
check      : |
    %make test
