name       : karchive
version    : 5.45.0
release    : 14
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.45/karchive-5.45.0.tar.xz : 18ae1f6639f3595ab048bb5a69fb91b5a941624512004da8365fd6299737883e
license    :
    - GPL-2.0
    - LGPL-2.1
component  : programming
optimize   : lto
summary    : Reading, creating, and manipulating file archives.
description: |
    Reading, creating, and manipulating file archives.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - bzip2-devel
    - extra-cmake-modules
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-building-unshipped-code.patch
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
