name       : karchive
version    : 5.78.0
release    : 48
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.78/karchive-5.78.0.tar.xz : 82e7a24280132b1654dc36caba52676b988a9feeaa6dbb9d398b170608f012d3
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.0-or-later
component  : programming.library
summary    : Reading, creating, and manipulating file archives.
description: |
    Reading, creating, and manipulating file archives.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Designer)
    - bzip2-devel
    - extra-cmake-modules
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
        -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
