name       : karchive
version    : 5.67.0
release    : 37
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.67/karchive-5.67.0.tar.xz : d6b8bc7d05dcb437dddfebd46d539d51eefe05bb0903cc13628770d80183ed82
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Reading, creating, and manipulating file archives.
description: |
    Reading, creating, and manipulating file archives.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - bzip2-devel
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
