name       : karchive
version    : 5.76.0
release    : 45
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.76/karchive-5.76.0.tar.xz : 503d33b247ae24260c73aac2c48601eb4f8be3f10c9149549ea5dd2d22082a2a
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.0-or-later
component  : programming.library
optimize   : lto
summary    : Reading, creating, and manipulating file archives.
description: |
    Reading, creating, and manipulating file archives.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - bzip2-devel
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
        -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
