name       : karchive
version    : 5.79.0
release    : 49
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.79/karchive-5.79.0.tar.xz : 0cd2bf46cc476b8b56138b3a892688ab70d0ddaa9739350a7421dc77a6210e07
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.0-or-later
component  : programming.library
summary    : Reading, creating, and manipulating file archives.
description: |
    Reading, creating, and manipulating file archives.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Designer)
    - bzip2-devel
    - extra-cmake-modules
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
        -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
