name       : karchive
version    : 5.78.0
release    : 47
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.78/karchive-5.78.0.tar.xz : 82e7a24280132b1654dc36caba52676b988a9feeaa6dbb9d398b170608f012d3
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.0-or-later
component  : programming.library
optimize   : lto
summary    : Reading, creating, and manipulating file archives.
description: |
    Reading, creating, and manipulating file archives.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - bzip2-devel
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
        -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
